User.create!([
  {email: "klstateler@hotmail.com", encrypted_password: "$2a$11$LlJVxzNzkWPIPfgdGUVzT.wm98NkgUw1wG0D5UzCdqhLIeiHdL7pq", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2018-05-04 13:54:06", last_sign_in_at: "2018-05-04 13:50:54", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", username: "kristines", is_admin: true}
])
Place.create!([
  {name: "Fenway Park", street_address: "4 Yawkey Way", city: "Boston", zip: "02155", description: "Fenway Park is a baseball park located in Boston, Massachusetts near Kenmore Square. Since 1912, it has been the home for the Boston Red Sox, the city's American League baseball team, and since 1953, its only Major League Baseball franchise.", category: "4", approved: true, user_id: 1, avatar: "275px-131023-F-PR861-033_Hanscom_participates_in_World_Series_pregame_events.jpg"},
  {name: "Boston Children's Museum ", street_address: "308 Congress St", city: "Boston", zip: "02110", description: "Boston Children's Museum is a children's museum in Boston, Massachusetts, dedicated to the education of children.", category: "3", approved: true, user_id: 1, avatar: "unnamed.jpg"},
  {name: "Boston Common", street_address: "139 Tremont St", city: "Boston", zip: "02111", description: "Boston Common is a central public park in downtown Boston, Massachusetts. It is sometimes erroneously referred to as the Boston Commons. Dating from 1634, it is the oldest city park in the United States.", category: "2", approved: true, user_id: 1, avatar: "download__5_.jpeg"},
  {name: "Boston Tea Party Ships & Museum", street_address: "306 Congress St", city: "Boston", zip: "02210", description: "Floating history museum with live reenactments, multimedia exhibits & a tearoom.", category: "3", approved: true, user_id: 1, avatar: "_H4C2923.jpg"},
  {name: "Freedom Trail", street_address: "0 Charles St", city: "Boston", zip: "02110", description: "The Freedom Trail is a 2.5-mile-long (4.0 km) path through downtown Boston, Massachusetts, that passes by 16 locations significant to the history of the United States. Marked largely with brick, it winds between Boston Common to the Bunker Hill Monument in Charlestown.", category: "1", approved: true, user_id: 1, avatar: "download__7_.jpeg"},
  {name: "Public Garden", street_address: "4 Charles St", city: "Boston ", zip: "02116", description: "America’s first public botanical garden, Public Garden was built in 1837 and has since been immortalised in literature and films including Good Will Hunting. The garden is home to several statues including “Bagheera” from The Jungle Book, but none are more prominent than Thomas Ball’s “Equestrian Statue of George Washington,” constructed in 1869.", category: "2", approved: true, user_id: 1, avatar: "Public-Garden.jpg"},
  {name: "Faneuil Hall", street_address: "4 S Market St", city: "Boston", zip: "02109", description: "Built in 1742, Faneuil Hall is one of Boston’s oldest landmarks and is rich in fascinating history. The marketplace and meeting hall has been the site of numerous independence speeches by prominent Americans such as Samuel Adams, with a bronze portrait statue standing outside. Known as “the Cradle of Liberty,” Faneuil Hall is nowadays part of a greater marketplace.  Open every day of the week, Faneuil Hall Marketplace treats visitors to local stalls selling delicious food, artisan goods, clothing, toys and more. There’s also regular entertainment each day such as live music and street performers. Less than a 10-minute walk from Faneuil Hall, The Langham Boston retains its own charming history dating back to Victorian England with elegant guest rooms draped in yesteryear opulence.", category: "1", approved: true, user_id: 1, avatar: "Faneuil-Hall.jpg"},
  {name: "Museum of Fine Arts", street_address: "465 Huntington Ave", city: "Boston", zip: "02115", description: "The past becomes present at Boston’s Museum of Fine Arts, home to more than 450,000 works of art. The building alone is worth the visit, built in 1909, but is merely a taste of the history and culture that awaits inside. The fourth-largest museum in the United States, the collection deals with cultures in America and around the world.  Highlights include 18th-century American artwork, Egyptian sculptures and sarcophagi, Chinese calligraphy, and paintings by Monet, Van Gogh and Renoir. These regular displays are joined by guest collections throughout the year. The museum also hosts programs for all ages covering film, music, performance art and studio art. Visitors can learn painting, drawing, printmaking and more alongside professional artists.", category: "3", approved: true, user_id: 1, avatar: "Museum-of-Fine-Arts.jpg"},
  {name: "Fort Independence", street_address: "2010 Day Boulevard", city: "Boston", zip: "02127", description: "Fort Independence is a granite bastion fort that provided harbor defenses for Boston, Massachusetts. Located on Castle Island, Fort Independence is one of the oldest continuously fortified sites of English origin in the United States", category: "1", approved: true, user_id: 1, avatar: "unnamed__1_.jpg"},
  {name: "TD Garden", street_address: "100 Legends Way", city: "Boston", zip: "02114", description: "TD Garden, often called Boston Garden the second or simply, The Garden, is a multi-purpose arena in Boston, Massachusetts. It is named after its sponsor, TD Bank, a subsidiary of Canada's Toronto-Dominion Bank.", category: "4", approved: true, user_id: 1, avatar: "unnamed__2_.jpg"},
  {name: "Matthews Arena", street_address: "238 St Botolph St", city: "Boston", zip: "02115", description: "Matthews Arena, in Boston, Massachusetts, is a basketball and ice hockey arena. It is the oldest indoor ice hockey arena still being used for hockey and is the oldest multi-purpose athletic building still in use in the world.", category: "4", approved: true, user_id: 1, avatar: "unnamed__3_.jpg"}
])
Review.create!([
  {title: "To much walking", body: "Very informational but the tour guides expected me to walk everywhere.....UGH", rating: 2, place_id: 5, user_id: 1},
  {title: "I learned so much!!!", body: "Great way to get around - just follow the path! Real easy and takes to you some great spots. If I was to do it again, I'd start at the end and work my way back into the city. Suggest subway and short walk out to the memorial and follow the route back in. This would lead you to a decent pit stop at Quincy then ending up at the park for ice cream. We had a cheeky lunch stop in little Italy, which was a treat and recommended.", rating: 5, place_id: 5, user_id: 1},
  {title: "Uugh. One big mall. Zero charm", body: "Stores that are available in any mall. Nothing unique or local. Not one ounce of charm. Needs a major over haul. Tons of tourists. And only tourists. Only go if you are walking through. No need to stop.", rating: 1, place_id: 7, user_id: 1},
  {title: "So disappointing!", body: "All I heard was “ have you gone to Faneuil Hall”? When you are expecting an old marketplace and see major store chains it loses all its charm. It was nothing more than outdoor mall with some bars, restaurants and some vendors with carts. There are a few boutiques worth browsing but again I cannot tell you why it’s such a big deal.", rating: 2, place_id: 7, user_id: 1},
  {title: "A vibrant lively place to enjoy", body: "We were lucky enough to be staying just round the corner from here, lovely place to spend a few hours, shops, bars, street entertainment, visiting from the U.K. it reminded me very much of the lovely Covent Garden, highly recommend!", rating: 5, place_id: 7, user_id: 1},
  {title: "Wonderful Place", body: "This is a lovely place to spend some time when the weather is nice! There were many, many families relaxing in the park. There's grassy areas for a picnic, a beach, paths for walking and jogging, and the fort. While the park does get pretty crowded on nice weekends, it was still a relaxing way to spend a couple of hours, and it's a great option for free family fun. \n", rating: 5, place_id: 9, user_id: 1},
  {title: "Great Touri", body: "This place is awesome. Well maintained piece of history. While a lot of the features inside are remakes and not original the overall structure and experience is amazing. For volunteers the tour guides are great and you can tell they take a lot of pride in what they do there.", rating: 4, place_id: 9, user_id: 1},
  {title: "Wow, rude emmployees", body: "The hotel is fine. In a good location, but I was not at all impressed by the employees. My problem started when I called to order room service and they called back in a few minutes letting me know that one item was unavailable. I said ok, I will look at the menu and call back. Before I even had a chance to look at the menu, another person from room service calls back demanding that I place my order or else they might need to make two trips. I said that I had not looked at the menu and needed more time. They replied I had to order right then, so I canceled the whole order. Later I spoke with the hotel manager and he told me the whole thing was a miscommunication. There was no miscommunication, but even if there was, a simple apology would have squashed it. Instead I left feeling like I was a problem for them. This may seem small and it is, but I felt like I wasn’t treated like a guest and I wasn’t taken seriously at all by the management. I was and am very disappointed by the employees at this hotel. I wished I had stayed somewhere else.", rating: 1, place_id: 3, user_id: 1},
  {title: "Beautiful Place to Enjoy the Day!", body: "Boston Common has many food trucks, (look for the cookie monster!) and is a nice relaxing place to go. Check out the duck boats!", rating: 5, place_id: 3, user_id: 1},
  {title: "Nice But...", body: "Not sure why this small public garden rates as high on TA. Quite small and has very little interest or feature other than a lake, plants and a duckling statue.", rating: 3, place_id: 6, user_id: 1},
  {title: "Quiet Stroll", body: "Tulips abound this time of year making a perfect picture. We enjoyed a lovely stroll through the Gardens taking in the warmth of the sun", rating: 4, place_id: 6, user_id: 1},
  {title: "One time to many", body: "Finally got to go to the CM today for the first time and despite the awesome location and outdoor areas, the experience was far from entertaining, perhaps because more than half of the exhibits were not working and no staff around to help kids with information or just simply to help whenever needed.\nDirt, yes there was dirt but then there was dirt on top of the dirt and that is just not right. How about the dated technology and obsolete interface. If you can pay $14 admission sure you have a smart phone with a lot more capability for learning, entertaining and interact with information than you will find here. If all you want is to get your kids tired, well a walk in the park is the way to go and more importantly, it is free and plus, you can have a snack or a drink while you are at it. ", rating: 1, place_id: 2, user_id: 1},
  {title: "boring", body: "Today we visited the Children's Museum and we were extremely disappointed. The museum and the exhibits were old, dirty and run-down. I have a 3 year old and 11 month old. The exhibits did not keep my 3 year olds attention for more then 30 seconds. The staff was nonexistent throughout the exhibits. We had a bad experience in the art room when my daughter swallowed paint. The art teacher could have cared less. She watched as my daughter cried and I caught her rolling her eyes. The baby space room was missing toys and the dolls and play clothes were disgusting and old. There just wasn't enough interaction for children. The whole museum needs to be updated with new technology, create new hands on exhibits and cleaned from top to bottom. They should take a look at the Science Museum or Walt Disney World. Both these institutions know how to entertain children. One positive, the museums exterior looked new and inviting.", rating: 2, place_id: 2, user_id: 1},
  {title: "Total Rip-Off for Toddlers", body: "Every one pay the ful price no matter what age. There is very few things to do for toddlers so it is not justified. If your kids are not at least 6 don't go there.", rating: 1, place_id: 2, user_id: 1},
  {title: "Steep Entry Fee", body: "At $25 with a AAA discount this site is not cheap. The program begins with costumed actors outlining the events leading up to the tea party. After this you board the ship and another actor discusses the events as they occurred aboard ship the evening of the tea party. Guests are then invited to throw symbolically overboard some boxes of tea re-enacting the event. You are then led down to the cargo hold where the tea was stored on board during the overseas voyage. Unfortunately on the day of my visit the fire alarm sounded and everyone was taken off the ship to the museum. There followed a holographic presentation outlining a conversation between a loyalist and “revolutionary” then a short movie describing Paul Reveres ride and the events leading up to and ultimately culminating in the battles at Lexington and Concord. At no point was there any attempt to re-board the ship to finish that part of the tour. In lieu of that everyone was offered a free cup of tea in the tea room upstairs. I think it was an overall good presentation, the actors were knowledgeable and enthusiastic and encouraged participation from the guests. However it was very expensive. It was the most that I paid for any historic site in town.", rating: 1, place_id: 4, user_id: 1},
  {title: "What A Great History Lesson", body: "When reading about this attraction, we thought maybe it would be a bit juvenile for two almost senior citizens. But it was quite interesting! We enjoyed the actors who led our tour, they did an excellent job, and the information provided was very educational, even for us! Toward the end of the tour, you'd think you were in a room created by Walt Disney! Good stuff!", rating: 5, place_id: 4, user_id: 1},
  {title: "Worth A Visit", body: "Definitely worth understanding this part of American/British history. Gives you an appreciation for those who came before us and who bravely spoke up against lack of representation and unfair taxes. Loved the part with the portraits who spoke!\n\n", rating: 4, place_id: 4, user_id: 1},
  {title: "Great Art, Horrible Custom Service", body: "This attraction is the essence of being run by people who are clueless about visitor experience but smart about art. The museum is laid out horrendously. Galleries are not marked well. The headphones are useless and half strangle you. It is not handicap friendly. The layout inside each gallery encourages bottle necks so that you're either suffocating in a crowd or in a nearly empty space. The security guards are rude and unhelpful, as are the staff generally, especially the restaurant staff. Bathrooms are oddly positioned. There's only one completely out of the way staircase to access the various floors. Worst of all, to exit several galleries you must exit the museum itself, being forced to show your tickets multiple times after waiting in multiple lines just to keep seeing the museum. I work in the tourism industry and cannot imagine an attraction screwing up in more ways than this one. I feel that for $25 I shouldn't have to fight to see the art, but that was the entirety of my experience. This museum needs to seriously overhaul its philosophy about customer service. The art is fantastic though!", rating: 2, place_id: 8, user_id: 1},
  {title: "You have to pay....", body: "Was not impressed that you had to pay to go in. Traveled all the way out to the museum on the subway , only to get there and come back. It was nice ride out but other than that was not impressed.", rating: 1, place_id: 8, user_id: 1},
  {title: "Where you can feel like Ferris Bueller", body: "The MOFA in Boston is such a great place to visit. You could actually spend hours in there and still not see everything there is to see. Then you can go back the next day or next weekend and you'll see things that you didn't see the first time. Now I am no art snob, nor an art critic or any other kind of art aficionado, but this is one place I love to walk around, often only to find myself standing and studying the paint strokes and intricate details of a priceless painting or the colored threads intertwining with such perfection to create a master tapestry. I can do this all day long. I guess I just like to stand and listen for what I think the art speaks to me. Well, maybe that's just me. I know, I'm a weirdo, or so I've been told. \nI don't know why, but it feels like a holy church of art and it deserves a hallowed reverence. So that's my token of appreciation to the timeless halls of the MOFA in Boston. \nGo early in the day or later in the afternoon. Less crowds and less little ones being a distraction. I think you'll be surprised what the paintings have to say to you, if you listen close enough... and that's all she wrote.", rating: 5, place_id: 8, user_id: 1},
  {title: "Baseball", body: "t was great to be at a ballgame! However this is the worst stadium for comfort and ammenities we have ever been too, and we have been to ALL the current parks and many of the old ones. Fenway was built when people were short, my knees were dug into the seat in front of me and i had to make small in my seat to avoid the person next to me. Signs and directions are terrible, we struggled getting in and out. Concessions for food were all unhealthy choices, however there were pleanty of booze everywhere. Ushers were non existent. I fail to see where Fenway rates as a major league park. At least there is baseball, boston deserves better.", rating: 1, place_id: 1, user_id: 1},
  {title: "The Spirit is Alive Here", body: "Such an cool ball park and the fans make it so! Be sure to where warm clothes if you sit in the stands in the shade, the wind blows in and it can be chilly.", rating: 5, place_id: 1, user_id: 1},
  {title: "Fenway Tour", body: "If you’re a fan of baseball I would definitely suggest doing a tour of Fenway! For only $22 they take you around the entire park and you get to see the ins and outs of everything! We loved it! So many photo opportunities too!", rating: 4, place_id: 1, user_id: 1},
  {title: "TD Garden Tour", body: "Very poor presentation of a sports arena , The Gardens is used by Bruins and Boston Celtics and after been on a behind scenes tour of Madison square gardens and many others , we felt disappointed with the tour , A little more info about the bruins than the Celtics , but even then very poor . you don't get to see much more than you might see if you are at a game honestly , its that poor of tour , We done Fen way and even though we are not baseball fans , the tour was far more interesting and delivered with passion", rating: 1, place_id: 10, user_id: 1},
  {title: "Worse Experience", body: "First time in Boston TD Garden. Atmosphere was fine but it smell horrible everywhere. I was greeted by this “nice” gentleman selling tickets, they looked legit but when tried to go into the stadium tickets DID NOT WORK! When tried to go back and find the “nice” gentleman, no where to be found. Total spam! Back where I’m from this never happened. Guess not everywhere is the same. STAY AWAY from ppl selling tickets outside stadium. Save yourself money and bad experience. Definitely ruined our night.", rating: 2, place_id: 10, user_id: 1},
  {title: "Impressive", body: "We hadn't seen a professional sports game for several years and this was a real treat. What a beautiful facility.We were in the VIP section with a suite with a nice buffet and a bartender. The Bruins won and it was a wonderful evening!", rating: 5, place_id: 10, user_id: 1},
  {title: "Nostalgic feel & Very Interesting!", body: "One of the oldest arenas in Boston. It definitely has a nostalgic feel. Interesting place to watch a northeastern hockey or basketball game, especially if you a are into watching a game at venues with an old time feel", rating: 5, place_id: 11, user_id: 1},
  {title: "Zero Parking", body: "Parking is Bad but facility is great with a lot of history in it", rating: 4, place_id: 11, user_id: 1},
  {title: "Great for Hockey & Basket Ball", body: "Nice arena for Hockey and Basketball. Great turnout from the Northeastern student body. Food is not great but it's a college arena and who goes there to eat? Seats are affordable and the fans are great.", rating: 4, place_id: 11, user_id: 1},
  {title: "Temperature isn't great", body: "It was chilly for the hockey game, wear warm clothes.", rating: 3, place_id: 11, user_id: 1}
])
